### ISSUE TITLE
Add a way to create temp DBs as root

### ISSUE THREAD

**Issue by ugtar** [ugtar/pg_temp#4]
Postgres doesn't want to allow creating a database directory (`initdb`) or run a server process as root.  Maybe if the root user attempts to create a TempDB we can try to set up the infrastructure as the postgres user, and allow connections from the root user.

**Comment by davvid** [comment]
i personally think it might be good to just leave the createuser part out of it and keep the rest as-is. looks solid. 

if they don't have a pg user a short snippet in the readme should suffice IMO. 

the runas context manager is a nice touch. q: after the euid and uid is changed to non-root, is it possible to become root again, or are those calls failing?

**Comment by ugtar** [comment]
so..
As far as `createuser`, it's a postgres script that's just a thin wrapper around `CREATE USER ...` that adds the current user as a superuser to the database.  This is necessary so the user running the tests can do whatever she likes in the temp db.  In most cases, the current user is also the one running `initdb`, so in that case the `createuser` call is a no-op (`initdb` automatically adds the caller as a superuser).  However, in the case of root where we must deescalate privs in order to create the db, we need to explicitly add the test-runner (root) as a superuser, since the user `initdb` ran as was 'postgres'.  Otherwise the user running as root won't be able to connect to the server she just created.

The `createuser` call is really only necessary in the cases where `check_user()` actually switches users.  I guess I could make the context manager yield an additional flag indicating whether or not the effective user was switched and only make the call in that case, but I was trying to limit the amount of logic intertwining the context manager and the code, and I figured the extra call to `createuser` wouldn't hurt even if it fails in all cases except root.

It may become more useful if we want to generalize the `check_user` functionality so that the `TempDB` can learn to create the db server as any user the caller wants, but I'm not sure if that's actually a real-life useful scenario.

In terms of euid, yes, you can deescalate and reescalate if you only change the effective id (euid--essentially the same as setting the setuid bit), however, if you also change the uid, you are changing your real id, and thus you lose your root privileges forever.  I tested this on linux and darwin, but I believe it's true on other Unixes as well.

I intended the context manager to simply temporarily set the euid and egid which I think would have been much cleaner, but it looks like the postgres guys are *very* concerned about the security implications of any pg bins executing as root (the code I linked to in the comment--I hope that link is somewhat stable) so simply changing the effective ids is not enough, you need to also run the commands with `su`.

**Comment by davvid** [comment]
ah, makes perfect sense now.
